site_name: 稲川淳二 恐怖の現場シリーズ ニコニコ動画まとめ

theme:
  name: material
  logo: material/ghost
  language: ja
  palette:

    # Dark mode (default)
    - scheme: slate
      primary: blue grey
      accent: red
      toggle:
        icon: material/weather-sunny
        name: ライトモードへ変更

    # Light mode
    - scheme: default
      primary: brown
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: ダークモードへ変更

# Extensions
markdown_extensions:
  - footnotes
  - pymdownx.tasklist:
      custom_checkbox: true
  - def_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - search
  - roamlinks
