site_name: 恐怖の現場 ニコ動まとめ

theme:
  name: material
  language: ja
  icon:
    logo: material/ghost
  favicon: images/favicon.svg
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - search.suggest
    - search.highlight
    
  palette:
    # Dark mode (default)
    - scheme: slate
      primary: black
      accent: red
      toggle:
        icon: material/eye-outline
        name: ライトモードへ変更

    # Light mode
    - scheme: default
      primary: brown
      accent: red
      toggle:
        icon: material/eye
        name: ダークモードへ変更
        
# Extensions
markdown_extensions:
  - footnotes
  - def_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

plugins:
  - search
  - roamlinks
